root: true

env:
  browser: true

extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"

rules:
  "@typescript-eslint/naming-convention": 1
  "@typescript-eslint/no-unused-vars": 0
  "curly": 1
  "eqeqeq": 2
  "prefer-const": 1

ignorePatterns:
  - "**/vendor/**"
